services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${SZ_DB_NAME}
      POSTGRES_USER: ${SZ_DB_USER}
      POSTGRES_PASSWORD: ${SZ_DB_PASS}
      PGPORT: ${SZ_DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${SZ_DB_PORT}:${SZ_DB_PORT}"

  api:
    build: .
    command: python /project/app/api.py
    volumes:
      - .secrets:/project/.secrets
      - .logs:/project/.logs
    ports:
      - "5200:5200"
    environment:
      - SZ_ENV=${SZ_ENV}
      - SZ_DB_NAME=${SZ_DB_NAME}
      - SZ_DB_USER=${SZ_DB_USER}
      - SZ_DB_PASS=${SZ_DB_PASS}
      - SZ_DB_HOST=db
      - SZ_DB_PORT=${SZ_DB_PORT}
      - SZ_LUM_CONTRACT_ADDRESS=${SZ_LUM_CONTRACT_ADDRESS}
      - SZ_LUM_ACCOUNT_PRIVATE_KEY=${SZ_LUM_ACCOUNT_PRIVATE_KEY}
      - SZ_ALCHEMY_API_KEY=${SZ_ALCHEMY_API_KEY}
    depends_on:
      - db
    extra_hosts:
      - "localhost:host-gateway"

volumes:
  postgres_data: