services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${SZ_DB_NAME}
      POSTGRES_USER: ${SZ_DB_USER}
      POSTGRES_PASSWORD: ${SZ_DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "35200:5432"

  api:
    build: .
    command: python /project/app/api.py
    volumes:
      - .secrets:/project/.secrets
      - .logs:/project/.logs
    ports:
      - "5200:5200"
    environment:
      - SZ_ENV=${SZ_ENV}
      - SZ_DB_NAME=${SZ_DB_NAME}
      - SZ_DB_USER=${SZ_DB_USER}
      - SZ_DB_PASS=${SZ_DB_PASS}
      - SZ_DB_HOST=db
      - SZ_DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: