project_id               = "eng-ai-dev"
environment              = "dev"
region                   = "us-central1"
zone                     = "us-central1-a"
resources_project_id     = "neat-airport-407301"