# Environment
local_env_name: local

# Logging
log_level: INFO
log_stdout: true
log_file: ./.logs/output.log

# GCP
gcp_project:  # Set this in each app-config file, separately; e.g. `gcp_project: eng-ai-dev`
job_start_topic: pipeline-zen-jobs-start
job_start_subscription:  # only needed in local env, set in local.yml
job_stop_topic: pipeline-zen-jobs-stop
heartbeat_topic:  # only needed in local env, set in local.yml
heartbeat_subscription: pipeline-zen-jobs-heartbeats-scheduler
mig_api_rate_limit: 100  # concurrent requests for GCP MIG API
gcs_pipeline_results_bucket_prefix: pipeline-zen-jobs  # Set this without the `lum-` prefix

# LUM
lum_rpc_url: https://eth-holesky.g.alchemy.com/v2/
lum_contract_address:  # Set this in your .env file: `SZ_LUM_CONTRACT_ADDRESS=.....`
lum_job_manager_abi_path: ./assets/job_manager_abi.json
lum_account_address: "0x4118CFD00dD5e8CED96e0ff8061F56F2d155e83B"
lum_account_private_key:  # Set this in your .env file: `SZ_LUM_ACCOUNT_PRIVATE_KEY=.....`
lum_job_monitor_interval_s: 60  # seconds
alchemy_api_key:  # Set this in your .env file: `SZ_ALCHEMY_API_KEY=.....`

# Domain logic
recently_completed_job_threshold_minutes: 10

# Database
# Set these in your .env file when running on a local env
# On non-local envs, we store these in a GCP secret and on VM attributes
db_name:
db_user:
db_pass:
db_host:
db_port:

# Fake services
use_fake_mig_client: false
use_fake_mig_client_with_pipeline: false

# Available GPU types and their supported regions
gpu_regions:
  v100:
    - us-central1
  a100-40gb:
    - asia-northeast1
    - asia-northeast3
    - asia-southeast1
    - europe-west4
    - me-west1
    - us-central1
    - us-east1
    - us-west1
    - us-west3
    - us-west4
  a100-80gb:
    - us-central1
    - us-east4
    - us-east5
    - asia-southeast1
  h100-80gb:
    - us-central1

# Available MIG clusters and their GPU types
mig_clusters:
  # V100
  1xv100: v100
  4xv100: v100
  8xv100: v100
  # A100-40GB
  1xa100-40gb: a100-40gb
  2xa100-40gb: a100-40gb
  4xa100-40gb: a100-40gb
  8xa100-40gb: a100-40gb
  # A100-80GB - $$$$$$ don't use these unless you know what you're doing
  1xa100-80gb: a100-80gb
  2xa100-80gb: a100-80gb
  4xa100-80gb: a100-80gb
  8xa100-80gb: a100-80gb
  # H100-80GB - $$$$$$$$ don't use these unless you know what you're doing
  8xh100-80gb: h100-80gb

# Max scale limits for each MIG
max_scale_limits:
  # V100
  1xv100: 8
  4xv100: 2
  8xv100: 1
  # A100-40GB
  1xa100-40gb: 16
  2xa100-40gb: 8
  4xa100-40gb: 4
  8xa100-40gb: 2
  # A100-80GB
  1xa100-80gb: 16
  2xa100-80gb: 8
  4xa100-80gb: 4
  8xa100-80gb: 2
  # H100-80GB
  8xh100-80gb: 1