# Environment
local_env_name: local

# Logging
log_level: INFO
log_stdout: true
log_file: ./.logs/output.log

# GCP
gcp_project: neat-airport-407301
heartbeat_topic: pipeline-zen-jobs-heartbeats
heartbeat_subscription: pipeline-zen-jobs-heartbeats-scheduler
mig_api_rate_limit: 100  # concurrent requests for GCP MIG API

# LUM
lum_rpc_url: wss://holesky.drpc.org
lum_contract_address: 0x76ebc106f195D8DA1bffC26390360a258E7dD8A4
lum_job_manager_abi_path: ./assets/job_manager_abi.json
lum_account_address: 0x4118CFD00dD5e8CED96e0ff8061F56F2d155e83B
lum_account_private_key:

# Database
# Set these in your .env file when running on a local env
# On non-local envs, we store these in a GCP secret
db_name:
db_user:
db_pass:
db_host:
db_port:

# Fake services
use_fake_mig_client: false

# Available GPU types and their supported regions
gpu_regions:
  v100:
    - us-central1
  a100-40gb:
    - asia-northeast1
    - asia-northeast3
    - asia-southeast1
    - europe-west4
    - me-west1
    - us-central1
    - us-east1
    - us-west1
    - us-west3
    - us-west4
  a100-80gb:
    - us-central1
    - us-east4
    - us-east5
    - europe-west4
    - asia-southeast1
  h100-80gb:
    - us-central1

# Available MIG clusters and their GPU types
mig_clusters:
  # V100
  1xv100: v100
  4xv100: v100
  8xv100: v100
  # A100-40GB
  1xa100-40gb: a100-40gb
  2xa100-40gb: a100-40gb
  4xa100-40gb: a100-40gb
  8xa100-40gb: a100-40gb
  # A100-80GB - $$$$$$ don't use these unless you know what you're doing
  1xa100-80gb: a100-80gb
  2xa100-80gb: a100-80gb
  4xa100-80gb: a100-80gb
  8xa100-80gb: a100-80gb
  # H100-80GB - $$$$$$$$ don't use these unless you know what you're doing
  8xh100-80gb: h100-80gb

# Max scale limits for each MIG
max_scale_limits:
  # V100
  1xv100: 8
  4xv100: 2
  8xv100: 1
  # A100-40GB
  1xa100-40gb: 16
  2xa100-40gb: 8
  4xa100-40gb: 4
  8xa100-40gb: 2
  # A100-80GB
  1xa100-80gb: 16
  2xa100-80gb: 8
  4xa100-80gb: 4
  8xa100-80gb: 2
  # H100-80GB
  8xh100-80gb: 1